<a href="https://colab.research.google.com/github/ahmad123576/Deep-Learning/blob/main/Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [9]:
df=pd.read_csv('/content/insurance.csv')
df.head()

age  affordability  have_insurance
0   22              1               0
1   25              0               0
2   47              1               1
3   52              0               0
4   46              1               1

In [10]:
# train test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordability']],df.have_insurance,test_size=0.2, random_state=25)

In [11]:
# scaling so that age and affordibility are in same scaling range
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100
X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [12]:
# keras
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=500)

Epoch 1/500


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 866ms/step - accuracy: 0.5833 - loss: 0.6641
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.5833 - loss: 0.6638
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5833 - loss: 0.6636
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6634
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 0.6632
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6630
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 0.6628
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5833 - loss: 0.6625
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6623
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5833 - loss: 0.6621
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.6619
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5833 - loss: 0.6617

In [13]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step - accuracy: 0.0000e+00 - loss: 0.9150


[0.9149643778800964, 0.0]

In [14]:
model.predict(X_test_scaled)
# our dataset is small, but we have to continue now

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[0.5004574],
       [0.6489801],
       [0.6335592]], dtype=float32)

In [15]:
y_test

13    0
12    0
0     0
Name: have_insurance, dtype: int64

In [16]:
# now get the value of weight and bias from model
coef,intercept=model.get_weights()

In [17]:
coef,intercept

(array([[1.340848 ],
        [0.6395462]], dtype=float32),
 array([-0.3870162], dtype=float32))

In [30]:
# w1=1.3, w2=0.6, b=-0.38

In [19]:
# sigmoid
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [20]:
X_test

age  affordability
13   29              0
12   27              1
0    22              1

In [23]:
# instead of model.predict we should make prediction fun.
def prediction_fun(age,affordability):
  weighted_sum=coef[0]*age+coef[1]*affordability+intercept
  return sigmoid(weighted_sum)
prediction_fun(0.29,1)

/tmp/ipython-input-19-2205566428.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.6550644182667464

In [24]:
prediction_fun(0.27,1)

/tmp/ipython-input-19-2205566428.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.6489800812548304

In [25]:
# now we have to implement gradient descent in plain python, but first we should calculate sigmoid and log_loss
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))


array([0.99999386, 0.5       , 0.73105858])

In [26]:
def log_loss(y_true,y_predicted):
  epsilon=1e-15
  y_predicted_new=[max(i,epsilon) for i in y_predicted]
  y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new=np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [27]:
# now its time to implement our final gradient descent
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [28]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordability'],y_train,1000,0.4631)

Epoch:0, w1:0.9908553543733406, w2:0.9639447917163442, bias:-0.0647602141055823, loss:0.6640616224292145
Epoch:1, w1:0.9855023350953848, w2:0.9320303297654488, bias:-0.12128424253397121, loss:0.6536187041842788
Epoch:2, w1:0.9835281551948476, w2:0.9039127743873843, bias:-0.17046459299958347, loss:0.6456853919641781
Epoch:3, w1:0.9845247142299337, w2:0.8792200855557273, bias:-0.21318135903689803, loss:0.6396769458526829
Epoch:4, w1:0.9881034234137634, w2:0.857574959608726, bias:-0.2502709202535725, loss:0.6351178390505849
Epoch:5, w1:0.9939047943416647, w2:0.8386118467612398, bias:-0.2825058543982329, loss:0.6316333187011979
Epoch:6, w1:1.0016036356507854, w2:0.8219882909179841, bias:-0.31058420662253167, loss:0.628935513753927
Epoch:7, w1:1.010910906288496, w2:0.8073914971049629, bias:-0.33512584945445806, loss:0.6268078403209961
Epoch:8, w1:1.0215732325054365, w2:0.7945412507421145, bias:-0.35667377351548746, loss:0.6250900661157517
Epoch:9, w1:1.0333709329410137, w2:0.783190262230783

(np.float64(6.617687064690023),
 np.float64(0.7868346717352566),
 np.float64(-3.084078282267086))

In [29]:
coef, intercept

(array([[1.340848 ],
        [0.6395462]], dtype=float32),
 array([-0.3870162], dtype=float32))

In [31]:
# we got same values by implementing gradient descent function in plain python