<a href="https://colab.research.google.com/github/ahmad123576/Deep-Learning/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
# import libraries
import pandas as pd
import numpy as np

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [26]:
reviews=['nice food',
        'amazing restaurant',
        'too good',
        'just loved it',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement'
]
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [27]:
one_hot("amazing restaurant",30)

[27, 20]

In [28]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[21, 23], [27, 20], [25, 12], [20, 3, 23], [7, 9, 20], [9, 23], [22, 9, 1], [19, 19], [19, 6], [23, 17]]


In [29]:
# padding
max_length=4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[21 23  0  0]
 [27 20  0  0]
 [25 12  0  0]
 [20  3 23  0]
 [ 7  9 20  0]
 [ 9 23  0  0]
 [22  9  1  0]
 [19 19  0  0]
 [19  6  0  0]
 [23 17  0  0]]


In [30]:
# word embedding
embeded_vector_size=5
model=Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [31]:
X=padded_reviews
y=sentiment

In [32]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [33]:
model.fit(X,y,epochs=50,verbose=0)

In [34]:
# evaluate the model
loss,accuracy=model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 299ms/step - accuracy: 1.0000 - loss: 0.6274


1.0

In [35]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [36]:
weights[13]

array([ 0.01419124,  0.00978956,  0.01227728,  0.03182847, -0.04001538],
      dtype=float32)

In [37]:
weights[2]

array([ 0.03935996,  0.00145026,  0.04161736, -0.02005806,  0.03990859],
      dtype=float32)